server {
    listen 80;
    
    root /usr/share/nginx/html;
    index index.html;

    # 1. Configuration du Reverse Proxy vers le Backend
    # "Si l'URL commence par /api, envoie la requête au service Kubernetes 'backend-service' sur le port 8000"
    location /api {
        proxy_pass http://backend-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Gestion du Frontend React
    # "Pour tout le reste, sers les fichiers statiques ou renvoie index.html (SPA)"
    location / {
        try_files $uri $uri/ /index.html;
    }
}