apiVersion: v1
kind: Service
metadata:
  name: sample-app-backend-service
  labels:
    app: sample-app-backend-pods
spec:
  type: ClusterIP
  selector:
    app: sample-app-backend-pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
