# k8s/postgres-init.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS news (
      id SERIAL PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      content TEXT,
      date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    INSERT INTO news (title, content) VALUES 
    ('Victoire des Bleus !', 'L''équipe de France a remporté son match 3-0 avec brio.'),
    ('Mercato : Surprise au PSG', 'Un nouveau joueur inattendu signe ce matin.'),
    ('Ronaldo : La retraite ?', 'La star portugaise évoque son avenir.');