# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: foot-secrets
type: Opaque
stringData:
  # En prod, on utiliserait base64, mais stringData est accepté par K8s et plus lisible pour l'apprentissage
  postgres-password: "footsecret"
  postgres-user: "postgres"
  postgres-db: "footnews"