apiVersion: v1
kind: Service
metadata:
  name: sample-app-frontend-loadbalancer
  labels:
    app: sample-app-frontend-pods
spec:
  type: LoadBalancer
  selector:
    app: sample-app-frontend-pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
