name: CI Pipeline Football News

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Étape 1 : Tests Unitaires (Critère Pédagogique : TDD) [cite: 15, 20, 193]
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - [cite_start]uses: actions/checkout@v3 # [cite: 231]
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        [cite_start]run: cd backend && npm install # [cite: 234]
      - name: Run Backend Tests
        [cite_start]run: cd backend && npm test # [cite: 236]

  # Étape 2 : Build et Push des images Docker [cite: 52, 85, 87]
  build-and-push:
    [cite_start]needs: test-backend # Ne build que si les tests passent [cite: 199, 200]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/foot-backend:latest 

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/foot-frontend:latest